name: Publish to GitHub Packages

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Configure Maven settings
      uses: s4u/maven-settings-action@v3
      with:
        servers: |
          [{
            "id": "github",
            "username": "${env.GITHUB_ACTOR}",
            "password": "${env.GITHUB_TOKEN}"
          }]
    
    - name: Update version for release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        mvn versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
    
    - name: Build and test
      run: mvn clean verify
    
    - name: Publish to GitHub Packages
      run: mvn deploy -DskipTests=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate artifacts summary
      run: |
        echo "## Published Artifacts" >> $GITHUB_STEP_SUMMARY
        echo "| Artifact | Version | SHA256 |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|---------|--------|" >> $GITHUB_STEP_SUMMARY
        cd target
        for file in *.jar; do
          if [[ "$file" != *"sources.jar" && "$file" != *"javadoc.jar" ]]; then
            sha256sum "$file" > "$file.sha256"
            checksum=$(cat "$file.sha256" | cut -d' ' -f1)
            echo "| $file | $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) | \`$checksum\` |" >> $GITHUB_STEP_SUMMARY
          fi
        done